/**
 * `agentguard init` — the 60-second install. Reads the agent's existing MCP config, probes the
 * servers, writes `agentguard.yaml` (dry-run by default) and rewrites the config so everything
 * goes through the proxy. `--undo` restores the backup.
 */
import { existsSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import YAML from "yaml";
import { type Upstream } from "@agentwares/agentguard-core";
import { flagBool, flagString, type ParsedArgs } from "../args.js";
import {
  describeConfigPath,
  detectClientConfigs,
  readServers,
  restoreClientConfig,
  rewriteClientConfig,
  serversToUpstreams,
  type ClientConfigFile,
} from "../configs.js";
import { homeFrom, policyPathFrom, type Io } from "../context.js";
import { probeUpstreams, type ProbedTool } from "./tools.js";

export interface StarterPolicyOptions {
  upstreams: Upstream[];
  tools?: ProbedTool[];
  mode?: "dry-run" | "enforce";
  generatedAt?: Date;
  probeErrors?: string[];
}

function dump(value: unknown, indent = 0): string {
  const text = YAML.stringify(value, { indent: 2, lineWidth: 100 }).trimEnd();
  const pad = " ".repeat(indent);
  return text
    .split("\n")
    .map((l) => pad + l)
    .join("\n");
}

function flow(list: string[]): string {
  return list.length === 0 ? "[]" : `[${list.map((s) => JSON.stringify(s)).join(", ")}]`;
}

/** The commented starter policy — the file people read, so every knob explains itself. */
export function renderStarterPolicy(opts: StarterPolicyOptions): string {
  const tools = opts.tools ?? [];
  const unknown = tools.filter((t) => t.classification.class === "unknown").map((t) => t.name);
  const destructive = tools
    .filter((t) => t.classification.destructive || t.classification.verb === "delete")
    .map((t) => t.name);
  const spend = tools.filter((t) => t.classification.class === "spend").map((t) => t.name);
  const date = (opts.generatedAt ?? new Date()).toISOString().slice(0, 10);
  const counts = tools.reduce<Record<string, number>>(
    (acc, t) => ({ ...acc, [t.classification.class]: (acc[t.classification.class] ?? 0) + 1 }),
    {},
  );
  const detected =
    tools.length === 0
      ? ["#   (no upstreams probed — run `agentguard tools` after fixing the upstreams above)"]
      : tools.map(
          (t) =>
            `#   ${t.name.padEnd(36)} ${t.classification.class.padEnd(8)} ${t.classification.verb.padEnd(8)} ${t.classification.source}: ${t.classification.reason}`,
        );
  const probeNotes = (opts.probeErrors ?? []).map((e) => `#   ! ${e}`);
  const upstreamsYaml = opts.upstreams.length
    ? dump({ upstreams: opts.upstreams.map(cleanUpstream) })
    : 'upstreams: []\n  # - name: crm\n  #   url: https://mcp.example.com/mcp\n  #   auth: ${CRM_TOKEN}\n  # - name: files\n  #   command: npx\n  #   args: [-y, "@modelcontextprotocol/server-filesystem", "."]';

  return `# agentguard.yaml — generated by \`agentguard init\` on ${date}
# Every knob is explained inline. Docs: https://github.com/agentwares/agentguard/tree/main/apps/agentguard-cli#policy
version: 1

# dry-run: reads pass through; writes and spends are FAKED (plausible success, nothing executes)
# and recorded. Run your agent once, then \`agentguard report\` and \`agentguard diff\`.
# Flip to \`enforce\` when the diff looks right. Caps and the loop breaker apply in both modes.
mode: ${opts.mode ?? "dry-run"}

# The servers your agent used to talk to directly. agentguard connects to them and holds their
# credentials; your agent only talks to agentguard. Use \${ENV_VAR} for secrets.
${upstreamsYaml}

# Detected tools (${tools.length}${
    tools.length
      ? `: ${Object.entries(counts)
          .map(([k, v]) => `${v} ${k}`)
          .join(", ")}`
      : ""
  }):
${[...detected, ...probeNotes].join("\n")}
# readOnlyHint annotations and verb heuristics classify most tools. List anything that is wrong here;
# these patterns win over annotations. \`*\` matches anything.
classify:
  read: []
  write: ${flow(unknown)}${unknown.length ? "   # could not be classified — treated as writes; move to read: if they only read" : ""}
  spend: ${flow(spend)}
  unknown: write   # a tool nobody can classify counts as a write (alternatives: read | block)

# Blast-radius caps. The call that would exceed a cap gets CAP_EXCEEDED with the remaining budget.
# \`writes\` counts every write or spend; \`deletes\`/\`emails\` count the subsets matched by \`counters\`.
caps:
  per_run:
    tool_calls: 400
    writes: 50
    deletes: 10
    emails: 5
    spend_usd: 25
  per_day:
    spend_usd: 200

# Dollar amounts. Declare how to read the amount from a spend tool's arguments; results reporting
# cost_usd / amount_usd are picked up automatically. Unknown spend tools cost \`default_usd\`.
spend:
  tools: {}
  #  stripe_create_charge: { amount_arg: amount, divisor: 100, currency_arg: currency }
  #  openai_*: { fixed_usd: 0.01 }
  default_usd: 0

# Semantic loop breaker: the same (tool, normalized arguments) ${3} times in the last 30 calls, or a
# repeating A→B→A→B cycle, returns LOOP_DETECTED. Timestamps, ids and whitespace are ignored.
loop:
  window: 30
  max_repeats: 3
  max_cycle_len: 4
  max_read_repeats: 10

# Always fake these, even in enforce mode. Remove entries as you gain trust.
dry_run:
  tools: []
  synthesize: true

# Destructive actions that need a human. The agent gets APPROVAL_REQUIRED with an id; you run
# \`agentguard approve <id>\` (or click the link in Slack); the agent retries the identical call once.
approval:
  tools: ${flow(destructive)}
  wait_s: 0          # > 0 holds the call open this long waiting for the decision
  ttl_s: 3600
  # notify:
  #   slack: \${SLACK_WEBHOOK_URL}

# Kill switch: \`agentguard kill\` creates this file (or POST /kill on the HTTP proxy); every call
# returns KILLED until \`agentguard resume\`. AGENTGUARD_KILL=1 in the environment does the same.
kill:
  file: .agentguard/KILL

# Scoped agent keys for the HTTP proxy: \`agentguard key create deployer --allow 'crm_get_*'\`.
# Only the key's hash is stored here; the agent sends the key as a Bearer token.
agents: []

# Alerts on halts (Slack incoming webhook or any HTTPS endpoint; signed with X-Agentwares-Signature).
# alerts:
#   slack: \${SLACK_WEBHOOK_URL}
#   on: [LOOP_DETECTED, CAP_EXCEEDED, KILLED, APPROVAL_REQUIRED]

# Hash-chained JSONL of every call; \`agentguard verify\` proves it was not edited.
audit:
  path: .agentguard/audit.jsonl
  redact: true
  include_results: false
`;
}

function cleanUpstream(u: Upstream): Record<string, unknown> {
  const out: Record<string, unknown> = { name: u.name };
  if (u.url) {
    out.url = u.url;
    if (Object.keys(u.headers).length) out.headers = u.headers;
  } else {
    out.command = u.command;
    if (u.args.length) out.args = u.args;
    if (Object.keys(u.env).length) out.env = u.env;
    if (u.cwd) out.cwd = u.cwd;
  }
  return out;
}

export async function initCommand(args: ParsedArgs, io: Io): Promise<number> {
  const policyPath = policyPathFrom(args, io);
  const explicit = flagString(args, "client");
  const configs: ClientConfigFile[] = explicit
    ? [describeConfigPath(resolve(io.cwd, explicit))]
    : detectClientConfigs(io.cwd, homeFrom(io), io.env);
  const rel = (p: string): string => {
    const r = relative(io.cwd, p);
    return r.startsWith("..") ? p : r || ".";
  };

  if (flagBool(args, "undo")) {
    let restored = 0;
    for (const c of configs) {
      if (restoreClientConfig(c)) {
        io.out(`restored ${rel(c.path)} from backup`);
        restored += 1;
      }
    }
    if (restored === 0)
      io.err("nothing to undo (no *.agentguard-backup files next to your MCP configs)");
    return 0;
  }

  // Only project-level configs are rewritten by default. User-level files (Claude Desktop,
  // ~/.cursor, Windsurf, ~/.claude.json) affect every project, so they need an explicit --client.
  const projectLevel = configs.filter((c) => c.path.startsWith(io.cwd + "/"));
  const userLevel = configs.filter((c) => !projectLevel.includes(c));
  let chosen: ClientConfigFile[];
  if (explicit) chosen = configs;
  else if (flagBool(args, "all")) chosen = configs;
  else chosen = projectLevel.slice(0, 1);
  if (!explicit && !flagBool(args, "all")) {
    for (const c of userLevel)
      io.out(
        `found   ${c.path} (${c.label}, user-level) — not touched; pass --client ${JSON.stringify(c.path)} to route it through agentguard`,
      );
  }
  if (!chosen.every((c) => existsSync(c.path))) {
    io.err(`no MCP config at ${chosen.map((c) => c.path).join(", ")}`);
    return 1;
  }

  const servers: Record<string, ReturnType<typeof readServers>[string]> = {};
  for (const c of chosen) {
    const found = readServers(c);
    io.out(
      `found   ${rel(c.path)} (${c.label}) → ${Object.keys(found).length} server${Object.keys(found).length === 1 ? "" : "s"}: ${Object.keys(found).join(", ") || "none"}`,
    );
    for (const [name, entry] of Object.entries(found))
      if (!(name in servers)) servers[name] = entry;
  }
  if (chosen.length === 0)
    io.out(
      "found   no MCP config (Claude Code .mcp.json, Cursor, VS Code, Claude Desktop, Windsurf) — writing a policy with no upstreams",
    );
  const { upstreams, skipped } = serversToUpstreams(servers);
  for (const s of skipped) io.err(`skipped ${s.name}: ${s.reason}`);
  if (
    skipped.some((s) => s.reason.includes("already")) &&
    upstreams.length === 0 &&
    existsSync(policyPath)
  ) {
    io.out(
      `already initialized: ${rel(policyPath)} exists and ${chosen.map((c) => rel(c.path)).join(", ")} already points at agentguard`,
    );
    return 0;
  }

  let probed: ProbedTool[] = [];
  const probeErrors: string[] = [];
  if (flagBool(args, "probe") !== false && upstreams.length > 0) {
    io.out(`probing ${upstreams.length} upstream${upstreams.length === 1 ? "" : "s"}…`);
    const result = await probeUpstreams(upstreams, {
      log: () => undefined,
      env: io.env,
      timeoutMs: 20_000,
    });
    probed = result.tools;
    for (const u of result.upstreams) {
      if (u.connected) io.out(`        ${u.name}: ${u.tools} tools`);
      else {
        io.err(
          `        ${u.name}: could not connect (${u.error}) — the proxy will keep retrying at start; fix the entry in agentguard.yaml`,
        );
        probeErrors.push(`${u.name}: ${u.error}`);
      }
    }
  }

  const mode = (flagString(args, "mode") as "dry-run" | "enforce" | undefined) ?? "dry-run";
  if (existsSync(policyPath) && !flagBool(args, "force")) {
    io.out(`kept    ${rel(policyPath)} (exists; pass --force to regenerate)`);
  } else {
    writeFileSync(policyPath, renderStarterPolicy({ upstreams, tools: probed, mode, probeErrors }));
    const counts = probed.reduce<Record<string, number>>(
      (acc, t) => ({ ...acc, [t.classification.class]: (acc[t.classification.class] ?? 0) + 1 }),
      {},
    );
    io.out(
      `wrote   ${rel(policyPath)} (mode: ${mode}, ${upstreams.length} upstream${upstreams.length === 1 ? "" : "s"}${
        probed.length
          ? `, ${probed.length} tools: ${Object.entries(counts)
              .map(([k, v]) => `${v} ${k}`)
              .join(", ")}`
          : ""
      })`,
    );
  }

  if (flagBool(args, "rewrite") !== false) {
    for (const c of chosen) {
      // `--config` names the policy file, and `--client` names the client's. Point both at the
      // same file — easy, because an MCP client's file is also called a config — and the
      // rewrite replaces the policy with the proxy entry and then points the proxy at that.
      // The upstreams survive only in the backup, and the proxy starts with nothing to guard.
      if (resolve(c.path) === resolve(policyPath)) {
        throw new Error(
          `refusing: ${rel(c.path)} is both the policy file (--config) and a client config. ` +
            `Rewriting it would replace the policy with the proxy entry and leave the proxy ` +
            `pointing at itself. Use --config for the policy path and --client for the ` +
            `client's config, or let --config default to agentguard.yaml.`,
        );
      }
      const { backup, replaced } = rewriteClientConfig(c, policyPath, {
        agent: flagString(args, "agent"),
      });
      io.out(
        `rewrote ${rel(c.path)} → ${replaced.length ? `${replaced.join(", ")} now go through` : "points at"} \`npx @agentwares/agentguard proxy\` (backup: ${rel(backup)})`,
      );
    }
  }

  io.out("");
  io.out("Next:");
  io.out(
    `  1. restart your MCP client so it re-reads ${chosen.map((c) => rel(c.path)).join(", ") || "its config"}`,
  );
  io.out(
    `  2. run your agent once — ${mode === "dry-run" ? "writes are faked; nothing executes upstream" : "enforce mode: caps, loop breaker and approvals are live"}`,
  );
  io.out("  3. agentguard report        # what this run would have destroyed / spent");
  io.out("     agentguard diff          # the record-by-record mutation diff");
  if (mode === "dry-run")
    io.out(`  4. set \`mode: enforce\` in ${rel(policyPath)} when it looks right`);
  io.out("  undo any time: agentguard init --undo");
  return 0;
}
